package principal;

import java.awt.Font;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author patri
 */
public class FrmLogin extends javax.swing.JFrame {
    public static sistema.Log log;
    public static sistema.Usuario usuario;
    public static sistema.Configuracoes conf;
    
    public static Font fontePadrao = new Font("Arial", Font.PLAIN, 12);
    public static Font fontePadraoNegrito = new Font("Arial", Font.BOLD, 12);

    public static boolean logado;
    private int contador;
    private FrmPrincipal frmPrincipal;
    
    public FrmLogin() {
        
        //the Nimbus look and feel
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //
        
        setResizable(false);
        initComponents();
        
        txtUsuario.requestFocus();
        
        logado = false;
        contador = 0;
        
        usuario = new sistema.Usuario(principal.Principal.conexao);
        
        log = new sistema.Log(principal.Principal.conexao);
        
        conf = new sistema.Configuracoes(principal.Principal.conexao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtUsuario = new lib.jdb.control.jdbtextfield.JDBTextField();
        lblSenha = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Tintas - OrionS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_OrionS/logotipo_login.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        lblNome.setFont(fontePadrao);
        lblNome.setText("Usuário:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, -1));

        lblSenha.setFont(fontePadrao);
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        pswSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(pswSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, -1));

        btnEntrar.setFont(fontePadrao);
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        btnEntrar.setMnemonic('E');
        btnEntrar.setText("Entrar");
        btnEntrar.setToolTipText("Entre com seu usuário e senha");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/wpp_550x224.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if(!logado){
            if(contador < 3){
                if(usuario.loginUsuario(
                        txtUsuario.getText().trim(), pswSenha.getText().trim())){
                    
                    txtUsuario.setText("");
                    pswSenha.setText("");
                    contador = 0;
                    
                    frmPrincipal = new FrmPrincipal(this);
                    frmPrincipal.setVisible(true);
                    logado = true;
                    
                    log.gravar(usuario.getNomeUsuario(), this, 0);
                    
                    txtUsuario.requestFocus();
                    
                    frmPrincipal.alterarTitulo();
                    
                    setVisible(false);
                }else{
                    contador ++;
                }
                txtUsuario.requestFocus();
            }
            if(contador == 3){
                JOptionPane.showMessageDialog(this, "Efetuado 3 tentativas de login inválidas.\n"
                        + "Fechando o sistema.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                
                dispose();
            }
        }else{
            
            if(contador < 3){
                if(usuario.loginUsuario(
                        txtUsuario.getText().trim(), pswSenha.getText().trim())){
                    
                    txtUsuario.setText("");
                    pswSenha.setText("");
                    contador = 0;
//                    
//                    new FrmPrincipal(this).setVisible(true);
//                    logado = true;
                    
                    log.gravar(usuario.getNomeUsuario(), this, 0);
                    
                    txtUsuario.requestFocus();
                    
                    frmPrincipal.alterarTitulo();
  
                    setVisible(false);
                }else{
                    contador ++;
                }
                txtUsuario.requestFocus();
            }
            if(contador == 3){
                JOptionPane.showMessageDialog(this, "Efetuado 3 tentativas de login inválidas.\n"
                        + "Fechando o sistema.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                
                dispose();
            }
        }
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if(evt.getKeyChar() == '\n'){
            pswSenha.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void pswSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSenhaKeyPressed
        if(evt.getKeyChar() == '\n'){
            btnEntrar.requestFocus();
        }
    }//GEN-LAST:event_pswSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField pswSenha;
    private lib.jdb.control.jdbtextfield.JDBTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void setFont(String arial, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
