/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author paulo
 */
public class iFrmBackup extends javax.swing.JInternalFrame {
    private sistema.Conexao conexao;
    private sistema.Backup bk;
    private FileFilter filtro;
    /**
     * Creates new form iFrmBackup
     */
    public iFrmBackup(sistema.Conexao conexao) {
        this.conexao = conexao;
        
        bk = new sistema.Backup(conexao);
        
        initComponents();
        
        selArquivo.setMultiSelectionEnabled(false);
        selArquivo.setControlButtonsAreShown(false);
        selArquivo.setDragEnabled(false);
        
        filtro = new FileFilter() {
            @Override
            public boolean accept(File f) {
                String[] temp = f.getPath().split("[.]");
                return temp[temp.length - 1].equals("sql");
            }

            @Override
            public String getDescription() {
                return "SQL";
            }
        };
                
//        selArquivo.setFileFilter(filtro);
//        selArquivo.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selArquivo = new javax.swing.JFileChooser();
        btnBackup = new javax.swing.JButton();
        btnRestore = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cópia de segurança e restauração do sistema");

        selArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selArquivoActionPerformed(evt);
            }
        });

        btnBackup.setText("Cópia de segurança");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });

        btnRestore.setText("Restauração");
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBackup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRestore))
                    .addComponent(selArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selArquivoActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        if(FrmLogin.usuario.verificarPermissao(this, 1)){
            
            if(sistema.Mensagem.showConfirmDialog(this, 
                    "Deseja realmente fazer o backup em:\n"
                    + selArquivo.getCurrentDirectory().getPath(), "Confirmação") == 0){

                if(bk.salvar(selArquivo.getCurrentDirectory())){
                    JOptionPane.showMessageDialog(this, "Backup realizado com sucesso!", 
                            "Atenção", JOptionPane.INFORMATION_MESSAGE);

                    selArquivo.rescanCurrentDirectory();
                    
                    // registro de log
                    FrmLogin.log.gravar(FrmLogin.usuario.getNomeUsuario(),
                            "iFrmBackup", "realizado backup sistema");
                }else{
                    JOptionPane.showMessageDialog(this, "Problema ao executar o backup!", 
                            "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnBackupActionPerformed

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
        if(FrmLogin.usuario.verificarPermissao(this, 2)){

            if(selArquivo.getSelectedFile() != null){
                if(filtro.accept(selArquivo.getSelectedFile())){
                    
                    if(sistema.Mensagem.showConfirmDialog(this, 
                            "Deseja realmente fazer a restauração do arquivo:\n"
                            + selArquivo.getSelectedFile().getPath() 
                            + "\nPor segurança, é necessário que nenhuma tarefa \n"
                            + "além do backup esteja aberta. \n"
                            + "Após a restauração for concluída, o sistema será FECHADO!",
                            "Confirmação") == 0){
                    
                        if(bk.restaurar(selArquivo.getSelectedFile())){
                            JOptionPane.showMessageDialog(this, 
                                    "Restauração realizada com sucesso!\n"
                                    + "Fechando o sistema", 
                                    "Atenção", JOptionPane.INFORMATION_MESSAGE);

                            selArquivo.rescanCurrentDirectory();

                            // registro de log
                            FrmLogin.log.gravar(FrmLogin.usuario.getNomeUsuario(),
                                    "iFrmBackup", "realizado restauração do sistema");
                            
                            //fechando o sistema após a restauração
                            System.exit(0);
                        }else{
                            JOptionPane.showMessageDialog(this, "Problema ao executar a restauração!", 
                                    "Atenção", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(this, 
                            "Arquivo com extensão inválida!", "Atenção", 
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, 
                        "Selecione um arquivo para fazer a restauração", "Atenção", 
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRestoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnRestore;
    private javax.swing.JFileChooser selArquivo;
    // End of variables declaration//GEN-END:variables
}
