/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package financeiro;

import java.text.DecimalFormat;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import lib.jdb.jdbquery.JDBQuery;
import lib.jdb.jdbupdate.JDBUpdate;
import principal.FrmLogin;

/**
 *
 * @author paulo
 */
public class iFrmDespesas extends javax.swing.JInternalFrame {
    String docFornecedor;
    int idDespesaLancCaixa, idCaixa;
    JDBQuery qryFornecedor, qryDespesaLancCaixa, qryCaixa, qryTemp;
    boolean pesquisaCaixa, pesquisaFornecedor;
    
    /**
     * Creates new form iFrmDespesas
     */
    public iFrmDespesas() {
        
        qryFornecedor = new JDBQuery();
        qryDespesaLancCaixa = new JDBQuery();
        qryCaixa = new JDBQuery();
        qryTemp = new JDBQuery();
        
        JDBQuery[] vetorQry = {qryFornecedor, qryDespesaLancCaixa, qryCaixa, qryTemp};
        for(JDBQuery qry: vetorQry){
            qry.setJDBConnection(principal.Principal.conexao.getConexao());
            qry.setConcurUpdatable(false);
            qry.setTimeStampFormat("dd/MM/YYYY HH:mm:ss");
            qry.setDateFormat("dd/MM/yyyy");
            qry.setLanguage("pt");
        }
        
        initComponents();
        
        calVencimento.setDateFormat(qryDespesaLancCaixa.getDateFormat());
        
        grpOpcoes.add(rdbAberto);
        grpOpcoes.add(rdbFechado);
        grpOpcoes.add(rdbTodos);
        
        tblLancamentos.setJDBQuery(qryDespesaLancCaixa);
        tblLancamentos.setEditable(false);
        tblLancamentos.setFieldsTitle("id", "CÓDIGO");
        tblLancamentos.setFieldsTitle("descricao", "DESCRIÇÃO");
        tblLancamentos.setFieldsTitle("valor", "VALOR");
        tblLancamentos.setFieldsTitle("movimento", "MOVIMENTO");
        tblLancamentos.setFieldsTitle("data_vencimento", "VENCIMENTO");
        tblLancamentos.setFieldsTitle("data_pagamento", "PAGAMENTO");
        tblLancamentos.setInvisibleFields("doc_principal_fornecedor id_item_caixa numero "
                + "data_inclusao data_modificacao");
        tblLancamentos.setFieldsWidth("descricao", 200);
        tblLancamentos.setFieldsWidth("id", 50);
                
        DecimalFormat decimal = new DecimalFormat("######0.00");        
        NumberFormatter numFormatter = new NumberFormatter(decimal);
        numFormatter.setFormat(decimal);
        numFormatter.setAllowsInvalid(false);
        DefaultFormatterFactory dfFactory = new DefaultFormatterFactory(numFormatter);
        
        txtValorTotal.setFormatterFactory(dfFactory);
        txtValor.setFormatterFactory(dfFactory);
        
        limpar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpOpcoes = new javax.swing.ButtonGroup();
        Painel1 = new javax.swing.JPanel();
        scrlCliente1 = new javax.swing.JScrollPane();
        tblLancamentos = new lib.jdb.control.jdbtable.JDBTable();
        pnCodigo1 = new javax.swing.JPanel();
        txtId = new lib.jdb.control.jdbtextfield.JDBTextField();
        pnCodigoCaixa1 = new javax.swing.JPanel();
        txtIdItemCaixa = new lib.jdb.control.jdbtextfield.JDBTextField();
        pnPagar1 = new javax.swing.JPanel();
        lblDataVenc1 = new javax.swing.JLabel();
        btnPagar = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        pnDatas1 = new javax.swing.JPanel();
        lblInc1 = new javax.swing.JLabel();
        txtInc = new lib.jdb.control.jdbtextfield.JDBTextField();
        lblMod1 = new javax.swing.JLabel();
        txtMod = new lib.jdb.control.jdbtextfield.JDBTextField();
        txtValor = new javax.swing.JFormattedTextField();
        lblValor2 = new javax.swing.JLabel();
        lblDataPag1 = new javax.swing.JLabel();
        txtCaixa = new javax.swing.JTextField();
        btnConsultarCaixa1 = new javax.swing.JButton();
        lblValor3 = new javax.swing.JLabel();
        txtDataPagto = new javax.swing.JTextField();
        btnLimparDespesa = new lib.jdb.control.jdbbuttoncancel.JDBButtonCancel();
        txtDescricao = new javax.swing.JTextField();
        lblDataVenc2 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblDataVenc3 = new javax.swing.JLabel();
        cbxMovimento = new javax.swing.JComboBox();
        calVencimento = new lib.jdb.control.jdbcalendar.JDBCalendar();
        lblValor4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnConsultar1 = new javax.swing.JButton();
        txtFornecedor = new javax.swing.JTextField();
        btnLimpar1 = new lib.jdb.control.jdbbuttoncancel.JDBButtonCancel();
        pnOpc1 = new javax.swing.JPanel();
        rdbAberto = new lib.jdb.control.jdbradiobutton.JDBRadioButton();
        rdbFechado = new lib.jdb.control.jdbradiobutton.JDBRadioButton();
        rdbTodos = new lib.jdb.control.jdbradiobutton.JDBRadioButton();
        txtValorTotal = new javax.swing.JFormattedTextField();
        lblFormaPagamento5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTotalCredito = new javax.swing.JFormattedTextField();
        lblFormaPagamento6 = new javax.swing.JLabel();
        txtTotalDebito = new javax.swing.JFormattedTextField();
        lblFormaPagamento7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Controle de despesas e movimentos de caixa");

        Painel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));

        scrlCliente1.setFont(principal.FrmLogin.fontePadrao);

        tblLancamentos.setEditable(false);
        tblLancamentos.setToolTipText("Duplo clique para selecionar");
        tblLancamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLancamentosMouseClicked(evt);
            }
        });
        scrlCliente1.setViewportView(tblLancamentos);

        pnCodigo1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)), "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        txtId.setFocusable(false);
        txtId.setFont(principal.FrmLogin.fontePadrao);

        javax.swing.GroupLayout pnCodigo1Layout = new javax.swing.GroupLayout(pnCodigo1);
        pnCodigo1.setLayout(pnCodigo1Layout);
        pnCodigo1Layout.setHorizontalGroup(
            pnCodigo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCodigo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCodigo1Layout.setVerticalGroup(
            pnCodigo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCodigo1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pnCodigoCaixa1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)), "Código de item de Caixa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        txtIdItemCaixa.setFocusable(false);
        txtIdItemCaixa.setFont(principal.FrmLogin.fontePadrao);

        javax.swing.GroupLayout pnCodigoCaixa1Layout = new javax.swing.GroupLayout(pnCodigoCaixa1);
        pnCodigoCaixa1.setLayout(pnCodigoCaixa1Layout);
        pnCodigoCaixa1Layout.setHorizontalGroup(
            pnCodigoCaixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCodigoCaixa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdItemCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCodigoCaixa1Layout.setVerticalGroup(
            pnCodigoCaixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCodigoCaixa1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txtIdItemCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pnPagar1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        lblDataVenc1.setFont(principal.FrmLogin.fontePadrao);
        lblDataVenc1.setText("Data de Vencimento:");

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N
        btnPagar.setMnemonic('p');
        btnPagar.setFont(principal.FrmLogin.fontePadrao);
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        pnDatas1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)), "Datas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        lblInc1.setFont(principal.FrmLogin.fontePadrao);
        lblInc1.setText("Inclusão:");

        txtInc.setFocusable(false);

        lblMod1.setFont(principal.FrmLogin.fontePadrao);
        lblMod1.setText("Modificação:");

        txtMod.setFocusable(false);

        javax.swing.GroupLayout pnDatas1Layout = new javax.swing.GroupLayout(pnDatas1);
        pnDatas1.setLayout(pnDatas1Layout);
        pnDatas1Layout.setHorizontalGroup(
            pnDatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDatas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInc1)
                    .addComponent(txtInc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnDatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMod1)
                    .addComponent(txtMod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDatas1Layout.setVerticalGroup(
            pnDatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDatas1Layout.createSequentialGroup()
                .addGroup(pnDatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDatas1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblInc1))
                    .addGroup(pnDatas1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMod1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnDatas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00#"))));

        lblValor2.setFont(principal.FrmLogin.fontePadrao);
        lblValor2.setText("Valor(R$):");

        lblDataPag1.setFont(principal.FrmLogin.fontePadrao);
        lblDataPag1.setText("Data de Pagamento:");

        txtCaixa.setToolTipText("Somente caixas abertos no dia corrente e do tipo normal podem ser usados nas vendas");
        txtCaixa.setFocusable(false);

        btnConsultarCaixa1.setFont(principal.FrmLogin.fontePadrao);
        btnConsultarCaixa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/look.png"))); // NOI18N
        btnConsultarCaixa1.setMnemonic('c');
        btnConsultarCaixa1.setText("Pesquisar");
        btnConsultarCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCaixa1ActionPerformed(evt);
            }
        });

        lblValor3.setFont(principal.FrmLogin.fontePadrao);
        lblValor3.setText("Caixa:");

        txtDataPagto.setFocusable(false);

        btnLimparDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/return2.png"))); // NOI18N
        btnLimparDespesa.setMnemonic('l');
        btnLimparDespesa.setFont(principal.FrmLogin.fontePadrao);
        btnLimparDespesa.setNextFocusableComponent(btnRemover);
        btnLimparDespesa.setText("Limpar");
        btnLimparDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDespesaActionPerformed(evt);
            }
        });

        lblDataVenc2.setFont(principal.FrmLogin.fontePadrao);
        lblDataVenc2.setText("Descrição");

        txtNumero.setNextFocusableComponent(txtValor);

        lblDataVenc3.setFont(principal.FrmLogin.fontePadrao);
        lblDataVenc3.setText("Número");

        cbxMovimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "débito", "crédito" }));

        calVencimento.setTextEditable(false);

        lblValor4.setFont(principal.FrmLogin.fontePadrao);
        lblValor4.setText("Movimento:");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnSalvar.setMnemonic('A');
        btnSalvar.setText("Adicionar");
        btnSalvar.setNextFocusableComponent(btnLimparDespesa);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        btnRemover.setMnemonic('r');
        btnRemover.setText("Remover");
        btnRemover.setNextFocusableComponent(btnPagar);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed1(evt);
            }
        });

        javax.swing.GroupLayout pnPagar1Layout = new javax.swing.GroupLayout(pnPagar1);
        pnPagar1.setLayout(pnPagar1Layout);
        pnPagar1Layout.setHorizontalGroup(
            pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPagar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPagar1Layout.createSequentialGroup()
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor4))
                        .addGap(18, 18, 18)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataVenc1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataPag1)
                            .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnPagar1Layout.createSequentialGroup()
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataVenc2)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataVenc3)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnPagar1Layout.createSequentialGroup()
                        .addComponent(pnDatas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblValor3)
                            .addComponent(txtCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultarCaixa1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnLimparDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnPagar1Layout.setVerticalGroup(
            pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPagar1Layout.createSequentialGroup()
                .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPagar1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalvar)
                        .addGap(21, 21, 21)
                        .addComponent(btnLimparDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPagar1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lblValor3))
                            .addGroup(pnPagar1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnRemover)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultarCaixa1)))
                    .addGroup(pnPagar1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataVenc2)
                            .addComponent(lblDataVenc3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPagar1Layout.createSequentialGroup()
                                .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnPagar1Layout.createSequentialGroup()
                                        .addComponent(lblValor2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(pnPagar1Layout.createSequentialGroup()
                                        .addComponent(lblValor4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtValor)
                                            .addComponent(cbxMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(pnPagar1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataPag1)
                                    .addComponent(lblDataVenc1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(18, 18, 18)
                        .addComponent(pnDatas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnConsultar1.setFont(principal.FrmLogin.fontePadrao);
        btnConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/look.png"))); // NOI18N
        btnConsultar1.setMnemonic('c');
        btnConsultar1.setText("Consultar");
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });

        txtFornecedor.setFocusable(false);

        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/return2.png"))); // NOI18N
        btnLimpar1.setMnemonic('l');
        btnLimpar1.setFont(principal.FrmLogin.fontePadrao);
        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });

        pnOpc1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        rdbAberto.setFont(principal.FrmLogin.fontePadrao);
        rdbAberto.setText("Aberto");
        rdbAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAbertoActionPerformed(evt);
            }
        });

        rdbFechado.setFont(principal.FrmLogin.fontePadrao);
        rdbFechado.setText("Fechado");
        rdbFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFechadoActionPerformed(evt);
            }
        });

        rdbTodos.setFont(principal.FrmLogin.fontePadrao);
        rdbTodos.setText("Todos");
        rdbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnOpc1Layout = new javax.swing.GroupLayout(pnOpc1);
        pnOpc1.setLayout(pnOpc1Layout);
        pnOpc1Layout.setHorizontalGroup(
            pnOpc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOpc1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbAberto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbFechado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnOpc1Layout.setVerticalGroup(
            pnOpc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnOpc1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(pnOpc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbAberto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbFechado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        txtValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00#"))));
        txtValorTotal.setFocusable(false);

        lblFormaPagamento5.setFont(principal.FrmLogin.fontePadrao);
        lblFormaPagamento5.setText("Valor total:");

        jLabel1.setText("Fornecedor:");

        txtTotalCredito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00#"))));
        txtTotalCredito.setFocusable(false);

        lblFormaPagamento6.setFont(principal.FrmLogin.fontePadrao);
        lblFormaPagamento6.setText("Total crédito:");

        txtTotalDebito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00#"))));
        txtTotalDebito.setFocusable(false);

        lblFormaPagamento7.setFont(principal.FrmLogin.fontePadrao);
        lblFormaPagamento7.setText("Valor débito:");

        javax.swing.GroupLayout Painel1Layout = new javax.swing.GroupLayout(Painel1);
        Painel1.setLayout(Painel1Layout);
        Painel1Layout.setHorizontalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addComponent(pnOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormaPagamento5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormaPagamento6)
                            .addComponent(txtTotalCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormaPagamento7))
                        .addGap(30, 30, 30)
                        .addComponent(btnLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar1))
                    .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrlCliente1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel1Layout.createSequentialGroup()
                            .addComponent(pnCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnCodigoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnPagar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel1Layout.setVerticalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar1)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel1Layout.createSequentialGroup()
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel1Layout.createSequentialGroup()
                                .addComponent(lblFormaPagamento5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel1Layout.createSequentialGroup()
                                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFormaPagamento6)
                                    .addComponent(lblFormaPagamento7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrlCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnCodigo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnCodigoCaixa1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPagar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLancamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLancamentosMouseClicked
        if(evt.getClickCount() == 2){
            carregarLancamento();
        }        
    }//GEN-LAST:event_tblLancamentosMouseClicked

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        if(FrmLogin.usuario.verificarPermissao(this, 1)){
        
            if(docFornecedor.isEmpty()){
                JOptionPane.showMessageDialog(this, "Consulte um fornecedor", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                btnConsultar1.requestFocus();
            }else if(idDespesaLancCaixa == 0){
                JOptionPane.showMessageDialog(this, "Selecione um lançamento para pagar", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }else if(!txtDataPagto.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Lançamento com pagamento já efetuado", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }else if(idCaixa == 0){
                JOptionPane.showMessageDialog(this, "Consulte um caixa para pagar", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                btnConsultarCaixa1.requestFocus();
            }else{

                if(sistema.Mensagem.showConfirmDialog(this,  
                        "Deseja realmente pagar este lançamento no caixa " + txtCaixa.getText(),
                        "Confirmação") == 0){

                    String sql = String.format(
                            "INSERT INTO itens_caixa("
                                + "id_caixa, "
                                + "descricao, "
                                + "valor, "
                                + "movimento) "
                            + "VALUES ("
                                + "'%s','%s','%s','%s')",
                            idCaixa,
                            txtFornecedor.getText() + " " + txtId.getText(),
                            txtValor.getValue(),
                            cbxMovimento.getSelectedIndex());
                    enviarTransacao(sql);

                    qryTemp.setSQL("SELECT LAST_INSERT_ID()");
                    qryTemp.execQuery();

                    int idItemcaixa = qryTemp.getCurrentFieldValueAsInteger(1);

                    sql = String.format(
                            "UPDATE despesas_lancamentos_caixa "
                            + "SET "
                                + "data_pagamento=now(), "
                                + "id_item_caixa='%s' "
                            + "WHERE id='%s'",
                            idItemcaixa,
                            idDespesaLancCaixa );
                    enviarTransacao(sql);
                    
                    FrmLogin.log.gravar(FrmLogin.usuario.getNomeUsuario(),
                           "iFrmDespesas", String.valueOf(idDespesaLancCaixa), "pagamento efetuado");

                }

                limparDespesa();
            }
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnConsultarCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCaixa1ActionPerformed
        pesquisaCaixa = true;
        pesquisaFornecedor = false;
        
        // campos para combobox sendo texto visual e o nome campo do banco referente.
        LinkedHashMap<String, String> combo = new LinkedHashMap<>();
        combo.put("Descrição", "descricao");
        combo.put("Código", "id");
        
        // titulos para as colunas da tabela, sendo texto visual e nome campo do banco referente.
        LinkedHashMap<String, String> titulo = new LinkedHashMap<>();
        titulo.put("CÓDIGO", "id");
        titulo.put("DESCRIÇÃO", "descricao");

        // campos que deseja deixar invisível, pode-se omitir.
        String[] invisivel = {"tipo"};

        // tamanho das colunas visíveis, pode-se omitir.
        int[] tamanho = null;
        
        pesquisa.iFrmPesquisa caixa;
        caixa = new pesquisa.iFrmPesquisa(this,
                "Pesquisa de Caixas",
                principal.Principal.conexao.getConexao(),
                qryCaixa,
                "id",
                combo,
                titulo,
                "SELECT id, descricao, tipo FROM vw_caixa_consulta_conta_pagar",
                invisivel,
                tamanho);
        
        principal.FrmPrincipal.Desktop.add(caixa);
        caixa.setVisible(true);
    }//GEN-LAST:event_btnConsultarCaixa1ActionPerformed

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
        limpar();
        
        pesquisaFornecedor = true;
        pesquisaCaixa = false;
        
        // campos para combobox sendo texto visual e o nome campo do banco referente.
        LinkedHashMap<String, String> combo = new LinkedHashMap<>();
        combo.put("Nome", "nome");
        combo.put("CNPJ", "doc_principal");
        
        // titulos para as colunas da tabela, sendo texto visual e nome campo do banco referente.
        LinkedHashMap<String, String> titulo = new LinkedHashMap<>();
        titulo.put("CNPJ", "doc_principal");
        titulo.put("NOME", "nome");

        // campos que deseja deixar invisível, pode-se omitir.
        String[] invisivel = null;

        // tamanho das colunas visíveis, pode-se omitir.
        int[] tamanho = null;
        
        pesquisa.iFrmPesquisa fornecedores;
        fornecedores = new pesquisa.iFrmPesquisa(this,
                "Pesquisa de fornecedor",
                principal.Principal.conexao.getConexao(),
                qryFornecedor,
                "doc_principal",
                combo,
                titulo,
                "SELECT doc_principal, nome "
                + "FROM vw_fornecedores_pesquisa_compra",
                invisivel,
                tamanho);
        
        principal.FrmPrincipal.Desktop.add(fornecedores);
        fornecedores.setVisible(true); 
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void rdbAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAbertoActionPerformed
        carregarQryDespesaLancCaixa();
    }//GEN-LAST:event_rdbAbertoActionPerformed

    private void rdbFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFechadoActionPerformed
        carregarQryDespesaLancCaixa();
    }//GEN-LAST:event_rdbFechadoActionPerformed

    private void rdbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTodosActionPerformed
        carregarQryDespesaLancCaixa();
    }//GEN-LAST:event_rdbTodosActionPerformed

    private void btnLimparDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDespesaActionPerformed
        limparDespesa();
    }//GEN-LAST:event_btnLimparDespesaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(FrmLogin.usuario.verificarPermissao(this, 1)){

            if(docFornecedor.isEmpty()){
                JOptionPane.showMessageDialog(this, "Consulte um fornecedor", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                btnConsultar1.requestFocus();
            }else if(txtDescricao.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Informe uma descrição", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtDescricao.requestFocus();
            }else if(Double.valueOf(txtValor.getValue().toString()) == 0.0){
                JOptionPane.showMessageDialog(this, "Informe uma valor", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                txtValor.requestFocus();
            }else if(calVencimento.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Informe uma data de vencimento", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                calVencimento.requestFocus();
            }else{
                // inserção
                if(idDespesaLancCaixa == 0){
                    String sql = String.format(
                            "INSERT INTO despesas_lancamentos_caixa("
                                    + "descricao, "
                                    + "doc_principal_fornecedor, "
                                    + "numero, "
                                    + "valor, "
                                    + "movimento, "
                                    + "data_vencimento) "
                                    + "VALUES ("
                                    + "'%s','%s','%s','%s','%s','%s')",
                            txtDescricao.getText(),
                            docFornecedor,
                            txtNumero.getText(),
                            txtValor.getValue(),
                            cbxMovimento.getSelectedIndex(),
                            calVencimento.getDateAsSQLDate());
                    enviarTransacao(sql);
                    
                    qryTemp.setSQL("SELECT LAST_INSERT_ID()");
                    qryTemp.execQuery();
                    String id = qryTemp.getCurrentFieldValueAsString(1);
                    
                    // registro de log
                    FrmLogin.log.gravar(FrmLogin.usuario.getNomeUsuario(),
                           this, id, 1);

                    limparDespesa();
                }else{
                    JOptionPane.showMessageDialog(this, "Limpe o lançamento atual para adicionar um novo", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    btnLimparDespesa.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed1
        if(FrmLogin.usuario.verificarPermissao(this, 2)){
        
            if(idDespesaLancCaixa == 0){
                JOptionPane.showMessageDialog(this, "Selecione um lançamento para excluir", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }else if(!txtDataPagto.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Lançamento pago, não pode ser excluido", 
                        "Atenção", JOptionPane.INFORMATION_MESSAGE);
            }else{

                if(sistema.Mensagem.showConfirmDialog(this, "Deseja realmente remover este lançamento?"
                        , "Confirmação") == 0){

                    String sql = "DELETE FROM despesas_lancamentos_caixa WHERE id = " 
                            + idDespesaLancCaixa;

                    enviarTransacao(sql);
                    
                    // registro de log
                    FrmLogin.log.gravar(FrmLogin.usuario.getNomeUsuario(),
                                this, String.valueOf(idDespesaLancCaixa), 3);

                }

                limparDespesa();
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed1


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel1;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnConsultarCaixa1;
    private lib.jdb.control.jdbbuttoncancel.JDBButtonCancel btnLimpar1;
    private lib.jdb.control.jdbbuttoncancel.JDBButtonCancel btnLimparDespesa;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave btnPagar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private lib.jdb.control.jdbcalendar.JDBCalendar calVencimento;
    private javax.swing.JComboBox cbxMovimento;
    private javax.swing.ButtonGroup grpOpcoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDataPag1;
    private javax.swing.JLabel lblDataVenc1;
    private javax.swing.JLabel lblDataVenc2;
    private javax.swing.JLabel lblDataVenc3;
    private javax.swing.JLabel lblFormaPagamento5;
    private javax.swing.JLabel lblFormaPagamento6;
    private javax.swing.JLabel lblFormaPagamento7;
    private javax.swing.JLabel lblInc1;
    private javax.swing.JLabel lblMod1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JLabel lblValor4;
    private javax.swing.JPanel pnCodigo1;
    private javax.swing.JPanel pnCodigoCaixa1;
    private javax.swing.JPanel pnDatas1;
    private javax.swing.JPanel pnOpc1;
    private javax.swing.JPanel pnPagar1;
    private lib.jdb.control.jdbradiobutton.JDBRadioButton rdbAberto;
    private lib.jdb.control.jdbradiobutton.JDBRadioButton rdbFechado;
    private lib.jdb.control.jdbradiobutton.JDBRadioButton rdbTodos;
    private javax.swing.JScrollPane scrlCliente1;
    private lib.jdb.control.jdbtable.JDBTable tblLancamentos;
    private javax.swing.JTextField txtCaixa;
    private javax.swing.JTextField txtDataPagto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtFornecedor;
    private lib.jdb.control.jdbtextfield.JDBTextField txtId;
    private lib.jdb.control.jdbtextfield.JDBTextField txtIdItemCaixa;
    private lib.jdb.control.jdbtextfield.JDBTextField txtInc;
    private lib.jdb.control.jdbtextfield.JDBTextField txtMod;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JFormattedTextField txtTotalCredito;
    private javax.swing.JFormattedTextField txtTotalDebito;
    private javax.swing.JFormattedTextField txtValor;
    private javax.swing.JFormattedTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables

    private void limpar(){
        docFornecedor = "";
        
        pesquisaCaixa = false;
        pesquisaFornecedor = false;
        
        txtFornecedor.setText("");
        txtValorTotal.setValue(0.0);
        txtTotalCredito.setValue(0.0);
        txtTotalDebito.setValue(0.0);
        
        rdbTodos.setSelected(true);
        
        limparDespesa();
    }
    
    private void limparDespesa(){
        idDespesaLancCaixa = 0;
        idCaixa = 0;
        
        txtId.setText("");
        txtIdItemCaixa.setText("");
        txtDescricao.setText("");
        txtNumero.setText("");
        txtValor.setValue(0.0);
        cbxMovimento.setSelectedIndex(0);
        calVencimento.setDateAsUtilDate(sistema.Data.getAtual());
        calVencimento.setText("");
        txtDataPagto.setText("");
        txtCaixa.setText("");
        txtInc.setText("");
        txtMod.setText("");
        
        txtDescricao.setFocusable(true);
        txtNumero.setFocusable(true);
        txtValor.setFocusable(true);
        cbxMovimento.setEnabled(true);
        
        carregarQryDespesaLancCaixa();
    }
    
    public void atribuirCampos(){
        if(pesquisaFornecedor){
            docFornecedor = qryFornecedor.getCurrentFieldValueAsString("doc_principal");
            txtFornecedor.setText(qryFornecedor.getCurrentFieldValueAsString("nome"));

            carregarQryDespesaLancCaixa();
            
            pesquisaFornecedor = false;
        }else if(pesquisaCaixa){
            idCaixa = qryCaixa.getCurrentFieldValueAsInteger("id");
            txtCaixa.setText(qryCaixa.getCurrentFieldValueAsString("descricao"));
            
            pesquisaCaixa = false;
        }
    }
    
    private void carregarQryDespesaLancCaixa(){        
        if(rdbAberto.isSelected()){
            qryDespesaLancCaixa.setSQL(String.format(
                    "SELECT "
                        + "id, "
                        + "descricao, "
                        + "doc_principal_fornecedor, "
                        + "id_item_caixa, "
                        + "numero, "
                        + "valor, "
                        + "CASE movimento WHEN 0 THEN 'débito' ELSE 'crédito' END AS 'movimento', "
                        + "data_vencimento, "
                        + "data_pagamento, "
                        + "data_inclusao, "
                        + "data_modificacao "
                    + "FROM "
                        + "despesas_lancamentos_caixa "
                    + "WHERE doc_principal_fornecedor = '%s' AND "
                        + "data_pagamento IS NULL "
                    + "ORDER BY data_vencimento",
                    docFornecedor) );
        }else if(rdbFechado.isSelected()){
            qryDespesaLancCaixa.setSQL(String.format(
                    "SELECT "
                        + "id, "
                        + "descricao, "
                        + "doc_principal_fornecedor, "
                        + "id_item_caixa, "
                        + "numero, "
                        + "valor, "
                        + "CASE movimento WHEN 0 THEN 'débito' ELSE 'crédito' END AS 'movimento', "
                        + "data_vencimento, "
                        + "data_pagamento, "
                        + "data_inclusao, "
                        + "data_modificacao "
                    + "FROM "
                        + "despesas_lancamentos_caixa "
                    + "WHERE doc_principal_fornecedor = '%s' AND "
                        + "data_pagamento IS NOT NULL "
                    + "ORDER BY data_pagamento",
                    docFornecedor) );
        }else{
            qryDespesaLancCaixa.setSQL(String.format(
                    "SELECT "
                        + "id, "
                        + "descricao, "
                        + "doc_principal_fornecedor, "
                        + "id_item_caixa, "
                        + "numero, "
                        + "valor, "
                        + "CASE movimento WHEN 0 THEN 'débito' ELSE 'crédito' END AS 'movimento', "
                        + "data_vencimento, "
                        + "data_pagamento, "
                        + "data_inclusao, "
                        + "data_modificacao "
                    + "FROM "
                        + "despesas_lancamentos_caixa "
                    + "WHERE doc_principal_fornecedor = '%s' "
                    + "ORDER BY data_inclusao",
                    docFornecedor) );
        }
        
        qryDespesaLancCaixa.execQuery();
        
        if(rdbTodos.isSelected()){
            txtValorTotal.setValue(0.0);
            
            txtTotalCredito.setValue(0.0);
            txtTotalDebito.setValue(0.0);
        }else{
            double soma[] = somarValores();
            txtValorTotal.setValue(soma[0]);
            
            txtTotalCredito.setValue(soma[1]);
            txtTotalDebito.setValue(soma[2]);
        }
    }
    
    private double[] somarValores(){
        double soma[] = {0.0, 0.0, 0.0};
        
        
        qryDespesaLancCaixa.first();
        if(qryDespesaLancCaixa.getRow() == 1){
            do{
                soma[0] += qryDespesaLancCaixa.getCurrentFieldValueAsDouble("valor");
                
                if(qryDespesaLancCaixa.getCurrentFieldValueAsString("movimento").equals("crédito")){
                    soma[1] += qryDespesaLancCaixa.getCurrentFieldValueAsDouble("valor");
                }else{
                    soma[2] += qryDespesaLancCaixa.getCurrentFieldValueAsDouble("valor");
                }
            }while(qryDespesaLancCaixa.next() != -1);
        }
        
        return soma;
    }
    
    private void enviarTransacao(String sql){
        JDBUpdate transacao = new JDBUpdate();
        transacao.setJDBConnection(principal.Principal.conexao.getConexao());

        transacao.setSQL(sql);
        transacao.setShowMessageOnError(true);
        
        transacao.execUpdate();
    }
    
    private void carregarLancamento(){
        int idItemCaixa;
        
        txtDescricao.setFocusable(false);
        txtNumero.setFocusable(false);
        txtValor.setFocusable(false);
        cbxMovimento.setEnabled(false);
        
        idDespesaLancCaixa = qryDespesaLancCaixa.getCurrentFieldValueAsInteger("id");

        txtId.setText(String.valueOf(idDespesaLancCaixa));
        txtDescricao.setText(qryDespesaLancCaixa.getCurrentFieldValueAsString("descricao"));
        txtNumero.setText(qryDespesaLancCaixa.getCurrentFieldValueAsString("numero"));
        txtValor.setValue(qryDespesaLancCaixa.getCurrentFieldValueAsDouble("valor"));
        cbxMovimento.setSelectedIndex(
                qryDespesaLancCaixa.getCurrentFieldValueAsString("movimento").equals("crédito")?1:0);
        calVencimento.setDateAsSQLDate(qryDespesaLancCaixa.getCurrentFieldValueAsSQLDate("data_vencimento"));        
        
        txtInc.setText(qryDespesaLancCaixa.getCurrentFieldValueAsString("data_inclusao"));
        txtMod.setText(qryDespesaLancCaixa.getCurrentFieldValueAsString("data_modificacao"));   

        if(qryDespesaLancCaixa.getCurrentFieldValueAsString("id_item_caixa") == null){
            idItemCaixa = 0;
        }else{
            idItemCaixa = qryDespesaLancCaixa.getCurrentFieldValueAsInteger("id_item_caixa");
        }
        txtIdItemCaixa.setText(String.valueOf(idItemCaixa));

        if(qryDespesaLancCaixa.getCurrentFieldValueAsSQLDate("data_pagamento") == null){
            txtDataPagto.setText("");
        }else{
            txtDataPagto.setText(qryDespesaLancCaixa.getCurrentFieldValueAsString("data_pagamento"));
        }
    }
}

