/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesquisa;

import estoque.iFrmCadPromocoes;
import lib.jdb.jdbquery.JDBQuery;

/**
 *
 * @author patri
 */
public class iFrmPesPromocao extends javax.swing.JInternalFrame {
    private String sqlOriginal;
    private iFrmCadPromocoes cadPromocoes;
    private JDBQuery qryOrigem;
    /**
     * Creates new form iFrmPesquisa
     */
    public iFrmPesPromocao(iFrmCadPromocoes cadPromocoes, JDBQuery qryOrigem) {
        this.cadPromocoes = cadPromocoes;
        this.qryOrigem = qryOrigem;
        
        initComponents();
        
        tbPromocao.setFieldsTitle("id", "CÓD.");
        tbPromocao.setFieldsTitle("id_produto", "CÓD.PRODUTO");
        tbPromocao.setFieldsTitle("nome", "PRODUTO");
        tbPromocao.setFieldsTitle("codigo_barra", "CÓD.BARRA");
        tbPromocao.setFieldsTitle("data_inicio", "INÍCIO");
        tbPromocao.setFieldsTitle("data_fim", "FIM");
        
        tbPromocao.setAutoResizeMode(tbPromocao.AUTO_RESIZE_OFF);
        tbPromocao.setFieldsWidth("id", 50);
        tbPromocao.setFieldsWidth("id_produto", 50);
        tbPromocao.setFieldsWidth("nome", 175);
        tbPromocao.setFieldsWidth("codigo_barra", 110);
        tbPromocao.setFieldsWidth("data_inicio", 120);
        tbPromocao.setFieldsWidth("data_fim", 120);
        
        tbPromocao.setInvisibleFields("valor_unitario quantidade valor_original data_inclusao data_modificacao");
        
        sqlOriginal = "SELECT id, id_produto, nome, codigo_barra, valor_unitario, "
                + "quantidade, valor_original, data_inicio, data_fim, data_inclusao, data_modificacao "
                + "FROM vw_promocoes";
        
        qryPesquisa.execQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qryPesquisa = new lib.jdb.jdbquery.JDBQuery();
        Painel = new javax.swing.JPanel();
        btnPesquisa = new javax.swing.JButton();
        scrlPromocao = new javax.swing.JScrollPane();
        tbPromocao = new lib.jdb.control.jdbtable.JDBTable();
        txtPesquisa = new javax.swing.JTextField();
        cbbPesquisa = new javax.swing.JComboBox<String>();
        lblQuantidadeItens = new javax.swing.JLabel();
        jDBLabelCount1 = new lib.jdb.control.jdblabelcount.JDBLabelCount();
        jSeparator1 = new javax.swing.JSeparator();
        lblDataInicial = new javax.swing.JLabel();
        lblDataFinal = new javax.swing.JLabel();
        chbAtiva = new lib.jdb.control.jdbcheckbox.JDBCheckBox();
        calFinal = new lib.jdb.control.jdbcalendar.JDBCalendar();
        calInicial = new lib.jdb.control.jdbcalendar.JDBCalendar();
        jButton1 = new javax.swing.JButton();

        qryPesquisa.setJDBConnection(principal.Principal.conexao.getConexao());
        qryPesquisa.setSQL("SELECT id, id_produto, nome, codigo_barra, valor_unitario, quantidade, valor_original, data_inicio, data_fim, data_inclusao, data_modificacao FROM vw_promocoes");
        qryPesquisa.setConcurUpdatable(false);
        qryPesquisa.setDateFormat("dd/MM/yyyy");
        qryPesquisa.setLanguage("pt");
        qryPesquisa.setTimeStampFormat("dd/MM/yyyy HH:mm:ss");
        qryPesquisa.setVisibleFields("");

        setClosable(true);
        setIconifiable(true);
        setTitle("Pesquisa de Promoções");
        setPreferredSize(new java.awt.Dimension(600, 418));

        Painel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        btnPesquisa.setFont(principal.FrmLogin.fontePadrao);
        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/look.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.setNextFocusableComponent(tbPromocao);
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        scrlPromocao.setFont(principal.FrmLogin.fontePadrao);

        tbPromocao.setJDBQuery(qryPesquisa);
        tbPromocao.setAutoCreateRowSorter(true);
        tbPromocao.setEditable(false);
        tbPromocao.setFont(principal.FrmLogin.fontePadrao);
        tbPromocao.setToolTipText("Duplo clique ou ENTER para carregar o registro");
        tbPromocao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbPromocaoKeyPressed(evt);
            }
        });
        tbPromocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPromocaoMouseClicked(evt);
            }
        });
        scrlPromocao.setViewportView(tbPromocao);

        txtPesquisa.setFont(principal.FrmLogin.fontePadrao);
        txtPesquisa.setToolTipText("");
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        cbbPesquisa.setFont(principal.FrmLogin.fontePadrao);
        cbbPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome produto", "Código barra", "Código produto", "Código promoção" }));

        lblQuantidadeItens.setFont(principal.FrmLogin.fontePadrao);
        lblQuantidadeItens.setText("Quantidade de itens:");

        jDBLabelCount1.setFont(principal.FrmLogin.fontePadrao);
        jDBLabelCount1.setjDBQuery(qryPesquisa);

        lblDataInicial.setFont(principal.FrmLogin.fontePadrao);
        lblDataInicial.setText("Data inicial:");

        lblDataFinal.setFont(principal.FrmLogin.fontePadrao);
        lblDataFinal.setText("Data final:");

        chbAtiva.setSelected(true);
        chbAtiva.setFont(principal.FrmLogin.fontePadrao);
        chbAtiva.setText("Ativa");
        chbAtiva.setToolTipText("Se marcado mostra somente as promoções ativas");
        chbAtiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAtivaActionPerformed(evt);
            }
        });

        calFinal.setDateFormat("dd/MM/yyyy");
        calFinal.setTextEditable(false);

        calInicial.setDateFormat("dd/MM/yyyy");
        calInicial.setTextEditable(false);

        jButton1.setText("Limpar data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrlPromocao, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataInicial)
                            .addComponent(calInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataFinal)
                            .addGroup(PainelLayout.createSequentialGroup()
                                .addComponent(calFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLayout.createSequentialGroup()
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLayout.createSequentialGroup()
                                .addComponent(lblQuantidadeItens)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDBLabelCount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLayout.createSequentialGroup()
                                .addComponent(cbbPesquisa, 0, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chbAtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisa)))))
                .addContainerGap())
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbAtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addComponent(lblDataInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addComponent(lblDataFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(scrlPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeItens)
                    .addComponent(jDBLabelCount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        setBounds(0, 0, 698, 424);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        if(evt.getKeyChar() == '\n'){
            pesquisar();
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        pesquisar();
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void tbPromocaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPromocaoMouseClicked
        if(evt.getClickCount() == 2){
            carregarPesquisaSelecionada();
        }
    }//GEN-LAST:event_tbPromocaoMouseClicked

    private void tbPromocaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPromocaoKeyPressed
        if(evt.getKeyChar() == '\n'){
            carregarPesquisaSelecionada();
        }
    }//GEN-LAST:event_tbPromocaoKeyPressed

    private void chbAtivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAtivaActionPerformed
        
    }//GEN-LAST:event_chbAtivaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calFinal.setText("");
        calInicial.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel;
    private javax.swing.JButton btnPesquisa;
    private lib.jdb.control.jdbcalendar.JDBCalendar calFinal;
    private lib.jdb.control.jdbcalendar.JDBCalendar calInicial;
    private javax.swing.JComboBox<String> cbbPesquisa;
    private lib.jdb.control.jdbcheckbox.JDBCheckBox chbAtiva;
    private javax.swing.JButton jButton1;
    private lib.jdb.control.jdblabelcount.JDBLabelCount jDBLabelCount1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblQuantidadeItens;
    private lib.jdb.jdbquery.JDBQuery qryPesquisa;
    private javax.swing.JScrollPane scrlPromocao;
    private lib.jdb.control.jdbtable.JDBTable tbPromocao;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
    
    private void pesquisar(){
        String sql = sqlOriginal, texto, ordem = "";
            
        //0=Nome produto, 1=Código barra, 2=Código produto, 3=Código promoção
        int indice = cbbPesquisa.getSelectedIndex();
        texto = txtPesquisa.getText();
        
        sql += " WHERE ";
        if(indice == 0){
            texto = texto.replaceAll(" ", "%");
            sql += String.format("nome LIKE '%%%s%%'", texto);
            ordem = "nome";
        }else if(indice == 1){
            texto = texto.replaceAll(" ", "%");
            sql += String.format("codigo_barra LIKE '%%%s%%'", texto);
            ordem = "codigo_barra";
        }else if(indice == 2){
            if(texto.isEmpty())
                sql += String.format("id_produto > 0", texto);
            else
                sql += String.format("id_produto = %s", texto);
            
            ordem = "id_produto";
        }else if(indice == 3){
            if(texto.isEmpty())
                sql += String.format("id > 0", texto);
            else
                sql += String.format("id = %s", texto);
            
            ordem = "id";                
        }
        
        if(chbAtiva.isSelected()){
            String data = sistema.Data.getAtualFormatada();
            
            sql += String.format(" AND data_inicio <= '%s' "
                    + "AND (data_fim >= '%s' OR data_fim IS NULL)", data, data);
        }
        
        if(!calInicial.getText().isEmpty()){
            sql += String.format(" AND data_inicio <= '%s'",
                    calInicial.getDateAsString());
            if(!calFinal.getText().isEmpty()){
                sql += String.format(" AND (data_fim >= '%s' OR data_fim IS NULL)",
                        calFinal.getDateAsString());
            }
        }
        
        
        sql += " ORDER BY data_inicio" + (ordem.isEmpty()?"":", " + ordem);
        
//        System.out.println(sql);
        
        qryPesquisa.setSQL(sql);
        qryPesquisa.execQuery();
    }

    private void carregarPesquisaSelecionada(){
        gerarQryPesquisa("id");

        cadPromocoes.atribuirCampos();
        
        // fecha pesquisa.
        doDefaultCloseAction();
//            dispose();
    }
    
    private void gerarQryPesquisa(String chave){
        // Alimentando a query origem com a informação clicada na tabela da pesquisa.
        String valor = qryPesquisa.getCurrentFieldValue(chave);

        // Formatação de campo tipo String, coloca-se aspas('') entre o valor capturado.
        if(qryPesquisa.getFieldTypeName(chave).equals("String")){
            qryOrigem.setSQL(sqlOriginal + " WHERE " + chave + " = '" + valor + "'");
        }else{
            qryOrigem.setSQL(sqlOriginal + " WHERE " + chave + " = " + valor);
        }

        qryOrigem.setConcurUpdatable(false);
        qryOrigem.setDateFormat("dd/MM/yyyy");
        qryOrigem.setTimeStampFormat("dd/MM/yyyy HH:mm:ss");
        qryOrigem.setLanguage("pt");
        qryOrigem.execQuery();
    }
}
